### ISSUE TITLE
TXHook功能性建议

### ISSUE THREAD

**Issue by CDPumpkin** [fuqiuluo/TXHook#13]
1. 在抓包页面长按某个包体后调用系统分享API将数据打包分享(同样适用于数据页面)。
2. 完善抓包信息页面的保存功能。
3. Tea解密如果密钥为空时尝试自动使用hook到的密钥解密，如果成功解密，将解密密钥填入密钥栏内。
4. 抓包过滤功能（针对某一cmd输出过滤其他包体或者在已有的包体中搜索指定cmd）。
5. 增加模块注入Hook成功的状态提示。

**Comment by fuqiuluo** [comment]
### 小菜一碟（下次一定）

**Comment by CDPumpkin** [comment]
6. 拦截指定cmd包的发送和接收。（小菜一碟？难度加大）
7. 在TXHook中发送指定封包。（小菜一碟？难度加大）
8. 可以将内容post到指定接收端上(TXHook将hook的包体存到本地然后点击刷新按钮才能在页面上显示，如果用户设置了ip和端口，可直接将数据给到指定接收端上(指PC)，就不用保存在本地了)。

**Comment by CDPumpkin** [comment]
ccccccccccccccccccc.
