### ISSUE TITLE
群又搜不到了~

### ISSUE THREAD

**Issue by ogli324** [fuqiuluo/TXHook#46]
群又搜不到了~  再开下吧 谢谢大佬

**Comment by DiamondHunters** [comment]
请进



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月7日(周二) 中午11:34
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [fuqiuluo/TXHook] 群又搜不到了~ (Issue #46)




 
群又搜不到了~  再开下吧 谢谢大佬
