### ISSUE TITLE
对8.8.33版本sharekey无法正常获取

### ISSUE THREAD

**Issue by CDPumpkin** [fuqiuluo/TXHook#5]
环境
Android11，MIUI12.5，Lsposed 6106，QQ8.8.33

说明
清除QQ全部数据后，再次清除TXHook的全部数据(手动删除TXHook目录)后，确认Lsposed框架TXHook模块的作用域为QQ，启动QQ后尝试登录(sharekey会在QQ启动时生成)，结束TXHook模块后台重新启动，“数据”页面“基础信息和QQ其他参数”均无任何有效内容且“抓包"页面刷新后无数据。

备注
在清除QQ数据之前正常使用。

**Comment by fuqiuluo** [comment]
错误无法复现，实验在8833版本qq可以进行数据获取，请重新尝试

1. 对于sharekey无法获取属于技术原因，预计会修复

**Comment by CDPumpkin** [comment]
> 错误无法复现，实验在8833版本qq可以进行数据获取，请重新尝试
> 
> 1. 对于sharekey无法获取属于技术原因，预计会修复

等待回执

**Comment by fuqiuluo** [comment]
从1.2.22版本开始sharekey由列表形式展现，展示所有获取到的k
![V5LHZ6IWQX22 5@ZP4KUJVN](https://user-images.githubusercontent.com/61898844/135910051-8f11fb2c-0e79-4d97-8a86-f5336581ae2d.jpg)
ey
