### ISSUE TITLE
PublicKey和Sharekey列表复制内容错误

### ISSUE THREAD

**Issue by CDPumpkin** [fuqiuluo/TXHook#7]
当复制PublicKey或者Sharekey某内容时，其复制的内容跟显示的内容无差异(显示什么内容就复制什么内容)...

![bug](https://user-images.githubusercontent.com/64207250/135948176-4df03639-ad28-4f02-9ed8-1603eb34fbba.png)

上图圈起来的内容点击复制后粘贴内容为7B90BC23056E3E8A73D015A0... ，得不到完整数据，PublicKey同理。

04002B1EA9F47CD6121F31EB...

### 2021-10-05-10-36 又发现了一个问题
Sharekey密钥列表中排名第一的内容始终是PublicKey数据，如上图所示。

**Comment by CDPumpkin** [comment]
![...](https://user-images.githubusercontent.com/64207250/135949097-15d6898d-8b19-4180-9d9d-3dccf3c41270.png)

我知道哪里有问题了，可我不会改代码🤦‍♂️

**Comment by CDPumpkin** [comment]
尝试在代码中新增一个aar变量来获取完整内容

**Comment by fuqiuluo** [comment]
![{A0Z3@RAASKPSMCO_FB6QUY](https://user-images.githubusercontent.com/61898844/135968947-f18b7ce2-dac3-48e2-8f09-01b984aa15a4.png)
问题尝试修复

**Comment by fuqiuluo** [comment]
问题将在1.2.25bate修复
