### ISSUE TITLE
gradle版本和插件不对应

### ISSUE THREAD

**Issue by 1749335128** [fuqiuluo/TXHook#77]
![image](https://user-images.githubusercontent.com/86713070/212334912-90dadf82-0410-4c6e-86a0-2874170464a0.png)

我下载的是作者最新的源码2022年5月份,我将版本Gradle version 升级到7.3.3并且重新导入,其他都没改。
![image](https://user-images.githubusercontent.com/86713070/212335612-d65f0b8f-e9f7-4b4e-a5ae-3c998f2e1ce5.png)
然后就报类型推断异常，还有类导入报错。
![image](https://user-images.githubusercontent.com/86713070/212335895-b370884b-0f21-4598-b98f-c7f34015d3af.png)
然后我手动添加类型，进行重新编译。
![image](https://user-images.githubusercontent.com/86713070/212336072-a35492b1-f17b-4651-b7a7-da0c93238558.png)
然后又报这个序列化异常，我寻思可能是改了Gradle version,所以插件也要升级一下。
我去看了这个serialization的版本是1.6.21，我改到了kotlin版本1.5.31，还是相同报错。
我用这个gradle从来都没有用来过，每次都是报错，我觉得大概率是插件和版本不一致的问题，我就去百度了相关kotlin和gradle版本之间对应关系，还是没有解决，希望有大佬能帮我解决一下，跪谢。

**Comment by fuqiuluo** [comment]
### 错误解释
你这个是Xposed依赖没有找到，也就是下图的所引用的东西，
![image](https://user-images.githubusercontent.com/61898844/212341488-442e6920-3645-4efd-9e17-dfa5f5330293.png)

### 错误原因
![image](https://user-images.githubusercontent.com/61898844/212342066-fc4ba789-b567-40fb-839d-74274503aef0.png)
目前MavenCenter仓库没有这个依赖，估计是要切换别的仓库了噢。

### 解决方法

1. 导入仓库**repo.spring.io**

2. **XposedHelper**是Xposed框架提供的一个API类，你可以尝试区maven仓库下载[jar包](https://mvnrepository.com/artifact/de.robv.android.xposed/api/82)，然后再导入jar(compileOnly)。

**Comment by 1749335128** [comment]
我从仓库下载了那两个文件，引入类不报错误了。
还是之前那个问题unresolved reference serializers，编译通过不了。

**Comment by fuqiuluo** [comment]
https://stackoverflow.com/questions/54752020/kotlin-serialization-unresolved-reference-serializer

**Comment by fuqiuluo** [comment]
https://github.com/Kotlin/kotlinx.serialization/issues/771
