### ISSUE TITLE
申请加群，目前正在开发支持多用户的PWA网页QQ（类似Icalingua3）

### ISSUE THREAD

**Issue by ParticleG** [fuqiuluo/TXHook#92]
Q 1135989508

**Comment by ParticleG** [comment]
[Aerodyne](https://github.com/ParticleG/aerodyne)
[Aerodyne Fastify](https://github.com/ParticleG/aerodyne-fastify)

**Comment by fuqiuluo** [comment]
已申请加好友，请同意

**Comment by ParticleG** [comment]
> 

已处理
